name: TexturePackGenerator

on:
  push:
    tags:
      - 'v1.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Replace Text # 文字列置換処理
        run: |
          cd ./pack

          # タグ名に置き換え
          sed -e "s/\${tag}/${{ github.ref_name }}/g" pack.mcmeta > pack.mcmeta_rep
          mv pack.mcmeta_rep pack.mcmeta

      - name: Run Generate Script # 生成スクリプトを実行
        run: |
          cd ./generate/scripts
          chmod +x ./generator.main.kts
          ./generator.main.kts 
          
          tree ../../tmp

      - name: Generate ZIP
        run: |
          cd ./out/TexturePack
          zip TexturePack -r ./*

      - name: mv Out Files
        run: |
          mkdir upload && mv out/TexturePack.zip upload/
          mv out/pack_map.json upload/

      - name: Upload Artifact #アーティファクトをアップロード
        uses: actions/upload-artifact@v3
        with:
          name: Release
          path: upload/*

      - name: GitHub Releases #Githubにリリース
        uses: softprops/action-gh-release@v1
        with:
          name: ShortLifeTexture - ${{ github.ref_name }}
          body: |
            ダウンロードはこちらから！
            [ダウンロード](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/TexturePack.zip)

            Build by ${{ github.actor }}
          files: upload/*
